In [1]:
import pandas as pd
import numpy as np
import tabulate

In [2]:
# Read data to csv
# to_csv
# index=False: drop the index when saving data file.

df_csv = pd.read_csv('my_csv.csv')
df_csv.to_csv('my_csv_saved.csv', index=False)

In [3]:
df_txt = pd.read_table('my_table.txt')

In [4]:
df_txt.to_csv('my_txt_saved.txt', sep='\t', index=False)

In [5]:
# to_markdown(), to_latex()
print(df_csv.to_markdown())

|    |   col1 | col2   |   col3 | col4   | col5     |
|---:|-------:|:-------|-------:|:-------|:---------|
|  0 |      2 | a      |    1.4 | apple  | 2020/1/1 |
|  1 |      3 | b      |    3.4 | banana | 2020/1/2 |
|  2 |      6 | c      |    2.5 | orange | 2020/1/5 |

In [6]:
print(df_csv.to_latex())

\begin{tabular}{lrlrll}
\toprule
 & col1 & col2 & col3 & col4 & col5 \\
\midrule
0 & 2 & a & 1.400000 & apple & 2020/1/1 \\
1 & 3 & b & 3.400000 & banana & 2020/1/2 \\
2 & 6 & c & 2.500000 & orange & 2020/1/5 \\
\bottomrule
\end{tabular}

In [8]:
# Two basci data structure in pandas
# 1. Series
# Consist of 4 parts: data, index, dtype, name
s = pd.Series(data = [100, 'a', {'dic':5}],
              index = pd.Index(['id1', 20, 'third'], name = 'my_idx'),
              dtype = 'object',
              name = 'my_name')
s

my_idx
id1             100
20                a
third    {'dic': 5}
Name: my_name, dtype: object

In [9]:
# Get these by .
s.values

array([100, 'a', {'dic': 5}], dtype=object)

In [10]:
s.index

Index(['id1', 20, 'third'], dtype='object', name='my_idx')

In [11]:
s.dtype

dtype('O')

In [12]:
s.name

'my_name'

In [13]:
# Retrieve single index value
s['third']

{'dic': 5}

In [14]:
# 2: DataFrame
data = [
    [1,'a',1.2],
    [2, 'b', 2.2],
    [3, 'c', 3.2]
]
# [表达式 for 变量 in 可迭代对象]
df = pd.DataFrame(data = data,
                  index = ['row_%d' %i for i in range(3)],
                  columns=['col_0', 'col_1', 'col_2'] )
df

       col_0 col_1  col_2
row_0      1     a    1.2
row_1      2     b    2.2
row_2      3     c    3.2

In [15]:
# Second way to create a dataframe
# 
df2 = pd.DataFrame(
    data = {
        'col_0':[1,2,3],
        'col_1':list('abc'),
        'col_2':[1.2, 2.2, 3.2]
    },
    index = [f'row_{i}' for i in range(3)]
)
df2

       col_0 col_1  col_2
row_0      1     a    1.2
row_1      2     b    2.2
row_2      3     c    3.2

In [16]:
# Retrieve the coresponding columns and the table consisting of several columns
df2['col_0']

row_0    1
row_1    2
row_2    3
Name: col_0, dtype: int64

In [17]:
df2[['col_0', 'col_1']]

       col_0 col_1
row_0      1     a
row_1      2     b
row_2      3     c

In [18]:
# df.values, retrieve the attributes
df2.values

array([[1, 'a', 1.2],
       [2, 'b', 2.2],
       [3, 'c', 3.2]], dtype=object)

In [ ]:
# Assign values to DataFrame without index and column
# By using dic, column names and index are assigned automatically
df3 = pd.DataFrame({
    'col_0':['a','b','c'],
    'col_1':[1, 2, 3],
    'col_2':["一","二", "三"]
})

df3

  col_0  col_1 col_2
0     a      1     一
1     b      2     二
2     c      3     三

In [22]:
# Normally, we assign column name and values

data = [['alice', 'bob', 'jack'], [2000, 5000, 3000], [23, 25, 27]]
df4 = pd.DataFrame(data,
                   columns = ['name', 'salary', 'age']
)
df4

    name salary   age
0  alice    bob  jack
1   2000   5000  3000
2     23     25    27

In [23]:
# !!! previous data block seems read data by row!
data = [['alice', 23, 2000], ['jack', 25, 3000], ['bob', 24, 5000]]
df5 = pd.DataFrame(
    data,
    columns = ['name','age','salary']
)
df5

    name  age  salary
0  alice   23    2000
1   jack   25    3000
2    bob   24    5000