In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.3.3'

In [ ]:
# Read csv file
# pd.read_csv(path to the csv file)
df_csv = pd.read_csv('my_csv.csv')
df_csv

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5

In [ ]:
# Read txt file
# pd.read_table(path to the txt file)
df_txt = pd.read_table('my_table.txt')
df_txt

   col1 col2  col3    col4      col5
0     2    a   1.4   apple  2020/1/1
1     3    b   3.4  banana  2020/1/2
2     6    c   2.5  orange  2020/1/5